### ISSUE TITLE
Dead links: hackathon and Open Source

### ISSUE THREAD

**Issue by hroncok** [honzajavorek/junior.guru#96]
https://junior.guru/practice/

> Pokud vlastní nápad nepřichází a mentor není po ruce, můžeš zkusit hackathon nebo Open Source.

https://junior.guru/practice/hackathons error 404
https://junior.guru/practice/opensource different error 404

**Comment by hroncok** [comment]
and https://junior.guru/practice/help

**Comment by honzajavorek** [comment]
Fixed, thanks!
